version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: backdev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data:
